SELECT g.USER_ID, g.NICKNAME,
CONCAT_WS(' ', g.CITY, g.STREET_ADDRESS1, g.STREET_ADDRESS2) 전체주소,
CONCAT_WS('-', LEFT(g.TLNO,3), MID(g.TLNO,4,4),RIGHT(g.TLNO,4)) TLNO
FROM USED_GOODS_USER g JOIN USED_GOODS_BOARD b ON g.USER_ID = b.WRITER_ID
GROUP BY b.WRITER_ID, g.NICKNAME
HAVING COUNT(b.WRITER_ID) >= 3
ORDER BY g.USER_ID DESC;