SELECT CONCAT('/home/grep/src/',f.BOARD_ID,'/',f.FILE_ID,f.FILE_NAME,f.FILE_EXT) FILE_PATH FROM USED_GOODS_FILE f
JOIN USED_GOODS_BOARD b ON f.BOARD_ID = b.BOARD_ID
WHERE b.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILE_PATH DESC